### ISSUE TITLE
Scrape game.prathamcms.org

### ISSUE THREAD

**Issue by antonio-cortes-perez** [learningequality/sushi-chef-pradigi#5]
Are these different games from the ones in prathamopenschool.org?

In prathamopenschool.org there is a Fun section, one option could be to put all the games from 
http://www.game.prathamcms.org/gamelist.html?lang=Hindi
under this section.

Note: game.prathamcms.org does not provide zip files similar to prathamopenschool.org

**Comment by laurenlichtman** [comment]
Yes, we now have the up-to-date repo cc: @ivanistheone can we close this?
